### ISSUE TITLE
-strict GWT compliation errors

### ISSUE THREAD

**Issue by xclayl** [stephenh/tessell#17]
When compiling Tessell GWT apps with -strict, it errors saying the Stub* super class can't be found. (StubView for example)

One option is to generate the stubs in another folder so that GWT compiler can ignore them.

**Comment by stephenh** [comment]
Interesting. I'll have to go try that...Tessell's gwt.xml file has several "exclude **/Stub*" lines that are supposed to avoid that. Maybe it's missing a few.

**Comment by stephenh** [comment]
I tried to reproduce it by enabling strict in my todomvc example:

https://github.com/stephenh/todomvc-tessell

And it seems fine? E.g. running ./gradlew compileGwt does not output any fatal errors.

**Comment by xclayl** [comment]
I downloaded the sample app and got the following error:

Errors occurred during the build.
Errors running builder 'Integrated External Tool Builder' on project 'todomvc-tessell'.
Exception occurred executing command line.
Cannot run program "D:\Lat Projects\tessell-todomvc-ant\todomvc-tessell\gradlew" (in directory "D:\Lat Projects\tessell-todomvc-ant\todomvc-tessell"): CreateProcess error=193, %1 is not a valid Win32 application
Exception occurred executing command line.
Cannot run program "D:\Lat Projects\tessell-todomvc-ant\todomvc-tessell\gradlew" (in directory "D:\Lat Projects\tessell-todomvc-ant\todomvc-tessell"): CreateProcess error=193, %1 is not a valid Win32 application

This seems to be related to gradle which I don't care about.

I think the next step is for me to create a new app from scratch and attempt to get this working with ant and when I get stuck, I'll ask you for help and include the source code.  Before i get started, do you support ant -- ie would you be willing to help me get this working with ant?

Cheers,
Clay

**Comment by stephenh** [comment]
If you're on Windows, there is a "gradlew.bat" file right next to "gradlew" that should work.

And, yes, you can invoke this from Ant; that is what we do internally; you just need a target that calls a "<java>" task that does the same thing as:

https://github.com/stephenh/todomvc-tessell/blob/master/build.gradle#L53

If you open the todomvc-tessell project in Eclipse, everything (the run codegen-on-change is already setup); if you're doing it from scratch, you can copy/paste the sample project, or look at:

http://www.tessell.org/gettingstarted.html

**Comment by xclayl** [comment]
I got my app working!

The issue was with the GWT xml file -- I forgot the &lt;source&gt; tags are relative to the XML and it worked when I moved the &lt;exclude&gt; to the right &lt;source&gt; tag.

Thanks for your help. :)

-Clay





---- On Wed, 25 Feb 2015 10:14:12 -0500 Stephen Haberman &lt;notifications@github.com&gt; wrote ---- 

If you're on Windows, there is a "gradlew.bat" file right next to "gradlew" that should work.
 And, yes, you can invoke this from Ant; that is what we do internally; you just need a target that calls a "" task that does the same thing as:
 https://github.com/stephenh/todomvc-tessell/blob/master/build.gradle#L53
 If you open the todomvc-tessell project in Eclipse, everything (the run codegen-on-change is already setup); if you're doing it from scratch, you can copy/paste the sample project, or look at:
 http://www.tessell.org/gettingstarted.html

**Comment by stephenh** [comment]
Great!

**Comment by stephenh** [comment]
(Er, sorry if I closed this prematurely; is the strict thing still an issue for you?)

**Comment by xclayl** [comment]
I'm happy.  Thanks for your help.
