### ISSUE TITLE
Getting started (Maven, WAB)

### ISSUE THREAD

**Issue by anton-johansson** [stephenh/tessell#25]
Hey! I really like the looks of this library and would like to try it out in our GWT-project. However, I'm having some problems getting started. I have a few questions:

  1. ~~I'm using GWT 2.7. Is this supported? I'm using tessell-user-3.0.10 and I see that it requires a dependency gwt-servlet-0.0.0-230c633. I'm using Maven, and it gets omitted for conflict with 2.7, but I assume that's no problem.~~

  2. How are the three libraries related to eachother? I assume only tessell-user is actually required at runtime? tessel-dev handles the interface-generation from *.ui.xml files and tessell-apt handles annotation processing at development time? Which versions should you use? Only dev and user seem to follow the same versioning.

  3. ~~We're deploying our GWT-application in an OSGi container. This means that we build our GWT-application as a WAB (web archive bundle) instead of a WAR. maven-bundle-plugin handles this. However, as soon as I add tessell-user 3.0.10 to the pom.xml, maven-bundle-plugin fails with an ArrayIndexOutOfBoundsException (never seen this before). Any idea about this? It gives me errors for pretty much every single class:
```Invalid class file: org/tessell/model/dsl/AttachBinder.class```
```Invalid class file: org/tessell/model/dsl/Binder.class```~~
...

  4. When adding the builder in Eclipse to allow it to generate the interfaces, it's added to the .classpath file if I'm not mistaken. It's a common best-practice to have Git/SVN-ignore on this file. m2e in Eclipse generates this file anyway. Instead, we would need something in the pom.xml that tells m2e to create this builder when importing the project. Do you know if this is possible? It could be done with the old maven-eclipse-plugin, but that doesn't work well with m2e (which is the successor).

Any help on this is much appreciated!

EDIT: See answers below

**Comment by anton-johansson** [comment]
Found some answers myself:

  1. tessell versions 3.0.0 and above seems to be directed against GWT 2.7 and Java 8. My bad. I will use latest 2.x.x instead (2.20.0).

  3. Changed to latest version of maven-bundle-plugin to get around this problem.

**Comment by anton-johansson** [comment]
Questions are answered, closing issue.

**Comment by stephenh** [comment]
Hi Anton, this is embarrassing, but gmail had been putting all of my github/forum posts into their new "Forums" tab, and I only just now saw this. Sounds like you're on the right track, and we're chatting now in gitter, which is great, but just wanted to explain why I hadn't commented on it sooner.

**Comment by anton-johansson** [comment]
No problem!
